<Button>

<MyLayout>
    canvas.before:
        Color:
            rgba: (240/255,240/255, 240/255, 1)
        Rectangle:
            size: self.size
            pos: self.pos


    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        padding: 10
        spacing: 10

        Button:
            text: "Hello world!"

        Button:
            text:"Good World!"

